version: '3.9'
services:
  teeheehee:
    image: socrates1024/err_err_ttyl
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
      - /tmp/tapp-ramdisk:/tmp/tapp-ramdisk
    ports:
      - "15001:5001"
    environment:
      - X_USERNAME=HennCamy
      - SQLITE_DB_PATH="./data/agents.db"
      - SECURE_FILE=/tmp/tapp-ramdisk/private.env
  replicatoor:
    image: socrates1024/replicatoor@sha256:85653ee1890ef367f1bdef89b2f24a0fc01341119cd0e08e79810d8fd82927da
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
      - /tmp/tapp-ramdisk:/tmp/tapp-ramdisk
    ports:
      - "14002:4001"
    environment:
      - SECURE_FILE=/tmp/tapp-ramdisk/private.env
      - CONTRACT=0x2c5032c6b1ec3d13acc81758d83e0b4478e153ff
      - ETH_RPC_PREFIX=https://base-mainnet.g.alchemy.com/v2/
      - CHAIN_ID=8453

